from enum import Enum


class AnnotationType(str, Enum):
    IMAGE_CLASSIFICATION = "IMAGE_CLASSIFICATION"
    OBJECT_DETECTION = "OBJECT_DETECTION"
    SEGMENTATION = "SEGMENTATION"
    TEXT_CLASSIFICATION = "TEXT_CLASSIFICATION"
    NAMED_ENTITY_RECOGNITION = "NAMED_ENTITY_RECOGNITION"
    AUDIO_TRANSCRIPTION = "AUDIO_TRANSCRIPTION"
    SPEAKER_LABELING = "SPEAKER_LABELING"


class AnnotationStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    IN_REVIEW = "IN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class AssignmentStatus(str, Enum):
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    COMPLETED = "COMPLETED"


class AnnotationShape(str, Enum):
    BOUNDING_BOX = "BOUNDING_BOX"
    POLYGON = "POLYGON"
    POINT = "POINT"
    TEXT_SPAN = "TEXT_SPAN"
    LABEL = "LABEL"
